### ISSUE TITLE
Implement new class ScheduleChain

### ISSUE THREAD

**Issue by DiTsi** [eslupmi/impulse#98]
Add new class to use as chain in `impulse.yml` 'application.chains'

Minimal config:
```yaml

application:
  chains:
    devops: # generate 'no steps' for this chain at any datetime (GMT+0)
      type: schedule
```

All features here:
```yaml
application:
  chains:
    devops:
      type: schedule # flag to interpret as SceduleChain, now simple Chain
      timezone: Asia/Tashkent # or another format "GMT+12" (it's in most not OK because of season time shift). Maybe we should use "TZ identifier" from here: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones. Users timezone to shift start_time / dow / doe
      schedule:
      - matchers: # if any of matchers is match, use theese steps
        - expr: dow / 2 == 0 # dow - day of week (https://stackoverflow.com/a/18919183). "0" and "Sun" formats allowed, "Sun" format is alias for digits
          start_time: 12:00 # 24:00 format
          duration: 9h
        - expr: doe % 2 == 0 # day of epoch (https://communities.gainsight.com/customer-success-cs-15/how-to-convert-epoch-time-to-date-10949?postid=49392#post49392)
          start_time: 12:00
          duration: 9h
        - expr: dow =~ "Mon|Tue|Wed" # interpret as 3 =~ "1|2|3". True
          start_time: 12:00
          duration: 12h
        # - expr: date = 2024-07-14 # absolute date should work too
        - expr: date == 2024-07-14 # FIX!
          start_time: 12:00
          duration: 12h
        - expr: date =~ "2024-07-14|2024-07-15" # absolute date should work too
          start_time: 12:00
          duration: 12h
        steps:
          - user: DiTsi
          - wait: 5m
          - user: Director
        steps:
        - user: DiTsi
        - wait: 5h
      - steps: # steps created if conditions above don't match
        - user_group: devops
```

Real example:
```yaml
application:
  chains:
    devops: # duty every two days
      type: schedule
      timezone: Asia/Tashkent
      schedule:
      - matchers:
        - expr: doe % 2 =~ "0|1"
          start_time: 10:00
          duration: 12h
        steps:
          - user: DiTsi
          - wait: 5m
          - user: Director
      - matchers:
        - expr: doe % 2 =~ "0|1"
          start_time: 22:00
          duration: 12h
        steps:
          - user: Oleg
          - wait: 5m
          - user: Director
      - matchers:
        - expr: doe % 2 =~ "2|3"
          start_time: 10:00
          duration: 12h
        steps:
          - user: Tanya
          - wait: 5m
          - user: Director
      - matchers:
        - expr: doe % 2 =~ "2|3"
          start_time: 22:00
          duration: 12h
        steps:
          - user: Kristina
          - wait: 5m
          - user: Director
      - steps: # default
        - user: Director
```
